# -*- coding: utf-8 -*-
"""unsubscribe_email.ipynb

Automatically generated by Colaboratory.

"""



import os

from outlook_msg import Message
email=[]
os.chdir('/content/drive/My Drive/新增資料夾 (3)')
for msgs in os.listdir():
    if msgs.startswith('未傳遞'):
        with open(msgs) as msg_file:
            msg = Message(msg_file)

# Contents are the plaintext body of the email
            print(msgs)
            msg=msg.body.split()
            for m in msg:
                if '@' in m:
                    email.append(m)
                    print(m)
                    break
print(len(email))


"""#檢查是否跟聯絡窗口名單重複"""

import pandas as pd

excelemail=[]
for sheet in range(3):
    df=pd.read_excel('/content/2020_APEC聯絡窗口0414.xlsx',sheet_name=sheet,skiprows=[0])
    email=df['電子信箱'].dropna().str.strip()
    excelemail.extend(list(email))
excelemail

semail=set(email)
sexcelemail=set(excelemail)
intersection=semail.intersection(sexcelemail)
intersection

for i in intersection:
    print(email.index(i))


"""#selenium刪除"""

from selenium import webdriver

options = webdriver.ChromeOptions()
options.add_argument('-no-sandbox')
options.add_argument('-headless')
options.add_argument('-disable-dev-shm-usage')


import time
for i,e in enumerate(email):
    wd = webdriver.Chrome('chromedriver',options=options)
    wd.get('https://www.ctasc.org.tw/02publication/CleanEmail.asp')
    print(wd.page_source) # results
    htmlid=wd.find_element_by_id('txtEmail')
    htmlid.send_keys(e)
    wd.find_element_by_id('SaveBtn').click()
    wd.close()
    time.sleep(1)
    print('finish',i+1,e)
print('run all')
